### ISSUE TITLE
Error: EACCES: permission denied when deploying NodeJS web app

### ISSUE THREAD

**Issue by JoshAnderson123** [microsoft/vscode-azureappservice#1267]
I have been using Azure App Service extension (Visual Studio Marketplace v0.16.1) in Visual Studio Code (version 1.37.1) to deploy a NodeJS web app, JA-6MP-Portfolio1. This was previously succesfull, but in the last week has stopped working. This is due to an EACCES error, which has cropped up recently despite no change in the code. Below is the output for deploying the web app in Visual Studio Code:

```
13:00:39 JA-6MP-Portfolio1: Creating zip package...
13:00:55 JA-6MP-Portfolio1: Starting deployment...
13:01:55 JA-6MP-Portfolio1: Fetching changes.
13:01:55 JA-6MP-Portfolio1: Cleaning up temp folders from previous zip deployments and extracting pushed zip file /tmp/zipdeploy/d5e28b94-958e-4034-b2ea-6c19634eef06.zip (103.58 MB) to /tmp/zipdeploy/extracted
13:02:11 JA-6MP-Portfolio1: Updating submodules.
13:02:11 JA-6MP-Portfolio1: Preparing deployment for commit id '14acc3bb56'. 13:02:11 JA-6MP-Portfolio1: Oryx-Build: Running kudu sync...
13:02:11 JA-6MP-Portfolio1: Command: kudusync -v 50 -f /tmp/zipdeploy/extracted -t /home/site/wwwroot -n /home/site/deployments/14acc3bb566247a2bb30d0a4a3516cb8/manifest -p /home/site/deployments/dd3fd7cb1e5f47f0a2c10c4f5aa893bb/manifest -i ".git;.hg;.deployment;.deploy.sh"
13:02:14 JA-6MP-Portfolio1: Kudu sync from: '/tmp/zipdeploy/extracted' to: '/home/site/wwwroot'
13:02:14 JA-6MP-Portfolio1: Ignoring: .deployment 13:02:14 JA-6MP-Portfolio1: Ignoring: .git
13:02:14 JA-6MP-Portfolio1: Error: EACCES: permission denied, mkdir '/home/site/wwwroot/node_modules/.bin'
13:02:14 JA-6MP-Portfolio1: \n/opt/Kudu/Scripts/starter.sh kudusync -v 50 -f /tmp/zipdeploy/extracted -t /home/site/wwwroot -n /home/site/deployments/14acc3bb566247a2bb30d0a4a3516cb8/manifest -p /home/site/deployments/dd3fd7cb1e5f47f0a2c10c4f5aa893bb/manifest -i ".git;.hg;.deployment;.deploy.sh"
13:02:14 JA-6MP-Portfolio1: App container will begin restart within 10 seconds.
13:02:23 JA-6MP-Portfolio1: Waiting for long running command to finish...
13:02:24: Deployment to "JA-6MP-Portfolio1" completed.
```
The browser returns an 'Application Error' message when you try to look at the website. The Azure logs return an error saying it can't find the express library - the very first line of code in the app.js file. This leads me to believe that Azure is unsucessfully deploying the app without realising.

Here is the output of the most recent application log from the Azure Portal:

```
2019-10-29T08:35:42.304696796Z   _____                               
2019-10-29T08:35:42.304733098Z   /  _  \ __________ _________   ____  
2019-10-29T08:35:42.304739598Z  /  /_\  \___   /  |  \_  __ \_/ __ \ 
2019-10-29T08:35:42.304744499Z /    |    \/    /|  |  /|  | \/\  ___/ 
2019-10-29T08:35:42.304748999Z \____|__  /_____ \____/ |__|    \___  >
2019-10-29T08:35:42.304754199Z         \/      \/                  \/ 
2019-10-29T08:35:42.304758799Z A P P   S E R V I C E   O N   L I N U X
2019-10-29T08:35:42.304763299Z 
2019-10-29T08:35:42.304767400Z Documentation: https://aka.ms/webapp-linux
2019-10-29T08:35:42.304771700Z NodeJS quickstart: https://aka.ms/node-qs
2019-10-29T08:35:42.304775900Z NodeJS Version : v10.14.2
2019-10-29T08:35:42.304780200Z 
2019-10-29T08:35:42.794209166Z /opt/startup/init_container.sh: line 32: [: ==: unary operator expected
2019-10-29T08:35:43.006297075Z Oryx Version : 0.2.20191004.5, Commit: 95ca7f51b147da7b085922507f46106c664ae2a3
2019-10-29T08:35:43.007048710Z 
2019-10-29T08:35:43.009692733Z Cound not find build manifest file at '/home/site/wwwroot/oryx-manifest.toml'
2019-10-29T08:35:43.010220858Z Could not find operation ID in manifest. Generating an operation id...
2019-10-29T08:35:43.010238059Z Build Operation ID: 21d94693-6e98-495b-9b6c-e0b487f8153e
2019-10-29T08:35:44.222324687Z Writing output script to '/opt/startup/startup.sh'
2019-10-29T08:35:44.231183101Z Running #!/bin/sh
2019-10-29T08:35:44.231816430Z 
2019-10-29T08:35:44.231833831Z # Enter the source directory to make sure the script runs where the user expects
2019-10-29T08:35:44.231840332Z cd "/home/site/wwwroot"
2019-10-29T08:35:44.231845432Z 
2019-10-29T08:35:44.234147039Z export NODE_PATH=$(npm root --quiet -g):$NODE_PATH
2019-10-29T08:35:44.234165640Z if [ -z "$PORT" ]; then
2019-10-29T08:35:44.241185468Z         export PORT=8080
2019-10-29T08:35:44.241272272Z fi
2019-10-29T08:35:44.241297873Z 
2019-10-29T08:35:44.241337075Z npm start
2019-10-29T08:35:50.627973055Z 
2019-10-29T08:35:50.628016858Z > portfoliowebsite@1.0.0 start /home/site/wwwroot
2019-10-29T08:35:50.628024758Z > node index
2019-10-29T08:35:50.628029758Z 
2019-10-29T08:35:51.221155269Z internal/modules/cjs/loader.js:583
2019-10-29T08:35:51.221191670Z     throw err;
2019-10-29T08:35:51.221198171Z     ^
2019-10-29T08:35:51.221202871Z 
2019-10-29T08:35:51.221207471Z Error: Cannot find module 'express'
2019-10-29T08:35:51.221212271Z     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
2019-10-29T08:35:51.221228372Z     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
2019-10-29T08:35:51.221345578Z     at Module.require (internal/modules/cjs/loader.js:637:17)
2019-10-29T08:35:51.221364778Z     at require (internal/modules/cjs/helpers.js:22:18)
2019-10-29T08:35:51.221369879Z     at Object. (/home/site/wwwroot/index.js:1:79)
2019-10-29T08:35:51.221375479Z     at Module._compile (internal/modules/cjs/loader.js:689:30)
2019-10-29T08:35:51.221380179Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
2019-10-29T08:35:51.221384879Z     at Module.load (internal/modules/cjs/loader.js:599:32)
2019-10-29T08:35:51.221389680Z     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
2019-10-29T08:35:51.221394480Z     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
2019-10-29T08:35:51.237937453Z npm ERR! code ELIFECYCLE
2019-10-29T08:35:51.247064279Z npm ERR! errno 1
2019-10-29T08:35:51.249192679Z npm ERR! portfoliowebsite@1.0.0 start: `node index`
2019-10-29T08:35:51.250114722Z npm ERR! Exit status 1
2019-10-29T08:35:51.266696596Z npm ERR! 
2019-10-29T08:35:51.267518235Z npm ERR! Failed at the portfoliowebsite@1.0.0 start script.
2019-10-29T08:35:51.268307372Z npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-10-29T08:35:51.370826061Z 
2019-10-29T08:35:51.372139223Z npm ERR! A complete log of this run can be found in:
2019-10-29T08:35:51.373431583Z npm ERR!     /root/.npm/_logs/2019-10-29T08_35_51_269Z-debug.log
```

**Comment by nturinski** [comment]
Hi @JoshAnderson123 

Thanks for reporting.  It looks like the Azure server is having issues running `npm install`.  No idea why it suddenly needs permissions to create a the `.bin` file.

As a workaround, could you try running `npm install` in your local directory and then deploying it to Azure?

**Comment by JoshAnderson123** [comment]
Hi @nturinski 

Thanks for the suggestion! Running `npm install` in the local directory still results in the same error unfortunately.

**Comment by nturinski** [comment]
Do you have the option to create a new web app and deploy it to that?  I'm not sure what would have caused access errors, unfortunately.

If that's not an option, you could try SSHing into the web app and see if you can run an `sudo npm install`.  SSH can be accessed by right-clicking your web app in the tree.

**Comment by JoshAnderson123** [comment]
I have tried to SSH to the web app but it was unable to establish a connection with the server (Timed Out). I do have an option to create a new web app and deploy to that, but this has unfortunately resulted in the same problem.

**Comment by nturinski** [comment]
Yeah, sorry that this happened. I know it's super frustrating for things to just break suddenly.  

I'm not sure if something changed on the platform or extension side that was causing this.  If it happens again and you happen to know how you can repro it, that'd be super helpful.  Otherwise, I'll try to keep an eye out for it when I do my regular dev/testing 😃
