### ISSUE TITLE
Error Investigation: "Central Directory corrupt."

### ISSUE THREAD

**Issue by nigarfin** [microsoft/vscode-azureappservice#1753]
We found that users are hitting an error "Central Directory corrupt" though very few issues are reported here.

Can you investigate why users are hitting this issue so we can improve the error message or solve the immediate problem which ends up failing the deployment?

Users on the free linux sku seem to be more impacted  based on my investigation. Could have something to do with the size of their project.

**Comment by racchen** [comment]
Hi @ejizba,  

This issue still exists on VScode version 0.20.0 and 0.21.0. If we ZIP the package ourselves and deployed by KUDU, it works fine. However, the same package received errors when deployed from VScode. Please help to check and any suggestions will be helpful. 

下午5:34:46 Zip package size: 9.97 MB
下午5:34:47 Fetching changes.
下午5:34:48 Cleaning up temp folders from previous zip deployments and extracting pushed zip file /tmp/zipdeploy/031XXX-56e2-XXXX-XXXX-83caf44dfXXX.zip (9.51 MB) to /tmp/zipdeploy/extracted
下午5:34:48 **Number of entries expected in End Of Central Directory does not correspond to number of entries in Central Directory.**
下午5:34:51 Deployment failed.

**Comment by nturinski** [comment]
Have you tried deploying with version 0.21.2?  We changed the archiver that we were using, so maybe that could resolve your issue?

**Comment by racchen** [comment]
@nturinski yes, we still encountered this issue on 0.21.2....

**Comment by nturinski** [comment]
@racchen What type of project are you deploying?  Are you deploying to a Linux or Windows web app?  And do you happen to have a project available online for me to try to reproduce this with?

**Comment by katiie** [comment]
I seem to have encountered this issue, is there any way around this?

**Comment by DaveC-PCL** [comment]
We have 3 people at our company who are experiencing the same Central Directory corrupt issue.  Strangely, one of my co-workers is able to install this extension without issue.  I have tried older versions down to 0.21.0 with no luck.  Not sure what is going on.

Here is my output log:

[2021-09-02 09:34:23.827] [renderer1] [error] Corrupt ZIP: end of central directory record signature not found: validating: Corrupt ZIP: end of central directory record signature not found
    at _.downloadInstallableExtension (vscode-file://vscode-app/c:/Users/dnchong/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:196354)
    at async _.doRun (vscode-file://vscode-app/c:/Users/dnchong/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:195331)

**Comment by fiveisprime** [comment]
Hey there @DaveC-PCL, looks like your issue is a bit different from the deployment issue others in this thread are seeing. Can you verify whether you're behind a proxy? If so, you'll need to add your proxy config using the `"http.proxy"` setting in VS Code (open settings and search for "proxy" and you'll see it).

It may be that your co-worker that is successfully able to install the extension already setup the proxy config or has the environment variables set from working on other projects.

Hopefully this helps!

**Comment by DaveC-PCL** [comment]
Hi @fiveisprime,

I think you are on to something here.  I'm pretty sure we are behind a proxy, but I just don't know all the info I need setup this config.  I'll look into this and let you know. 

thanks
Dave

**Comment by karrivinodh** [comment]
> We found that users are hitting an error "Central Directory corrupt" though very few issues are reported here.
> 
> Can you investigate why users are hitting this issue so we can improve the error message or solve the immediate problem which ends up failing the deployment?
> 
> Users on the free linux sku seem to be more impacted based on my investigation. Could have something to do with the size of their project.



> Hi @ejizba,
> 
> This issue still exists on VScode version 0.20.0 and 0.21.0. If we ZIP the package ourselves and deployed by KUDU, it works fine. However, the same package received errors when deployed from VScode. Please help to check and any suggestions will be helpful.
> 
> 下午5:34:46 Zip package size: 9.97 MB 下午5:34:47 Fetching changes. 下午5:34:48 Cleaning up temp folders from previous zip deployments and extracting pushed zip file /tmp/zipdeploy/031XXX-56e2-XXXX-XXXX-83caf44dfXXX.zip (9.51 MB) to /tmp/zipdeploy/extracted 下午5:34:48 **Number of entries expected in End Of Central Directory does not correspond to number of entries in Central Directory.** 下午5:34:51 Deployment failed.

yes iam facing the issue

**Comment by karrivinodh** [comment]
have u solved this error

**Comment by karrivinodh** [comment]
> We are now getting this error after our zip has pushed past 2GB. Error did not occur until we added more assets to the app. I'm assuming there may be a 2GB limit to the zip itself?
> 
> ```
> 11:27:48 AM TheApp: Starting deployment...
> 11:27:49 AM TheApp: Creating zip package...
> 11:27:49 AM TheApp: Ignoring files from "appService.zipIgnorePattern"
> "node_modules{,/**}"
> "dist{,/**}"
> ".vscode{,/**}"
> 11:30:00 AM TheApp: Zip package size: 2.21 GB
> 11:30:29 AM TheApp: Fetching changes.
> 11:30:29 AM TheApp: Cleaning up temp folders from previous zip deployments and extracting pushed zip file C:\local\Temp\zipdeploy\yikasg1x.zip (0.00 MB) to C:\local\Temp\zipdeploy\extracted
> 11:30:30 AM TheApp: Central Directory corrupt.
> 11:30:34 AM TheApp: Deployment failed.
> ```

have you solved this error

**Comment by adejeg** [comment]
Can someone please help

19:54:11 hefa-iss: Starting deployment...
19:54:26 hefa-iss: Creating zip package...
19:54:26 hefa-iss: Zip package size: 22 B
19:54:32 hefa-iss: Fetching changes.
19:54:32 hefa-iss: Cleaning up temp folders from previous zip deployments and extracting pushed zip file C:\local\Temp\zipdeploy\3ruycmwv.zip (0.00 MB) to C:\local\Temp\zipdeploy\extracted
19:54:32 hefa-iss: Central Directory corrupt.
19:54:44 hefa-iss: Deployment failed.


I got this error log while trying to deploy an angular app using Azure App Service. I deployed earlier and everything was fine but now I don't even know where to begin.

**Comment by karrivinodh** [comment]
check your azure  resources. i think those resources are over

**Comment by adejeg** [comment]
Can you please explain?

I have uninstalled all azure resources, restarted my mac then reinstalled App Service but still faced the same challenge

**Comment by karrivinodh** [comment]
Iam talking about azure cloud resources go and check in microsoft azure.com

**Comment by adejeg** [comment]
Thanks for your feedback, but I am all lost on azure as I am new to the platform, please help me with some direction.

**Comment by karrivinodh** [comment]
you have to sign in to the azure portal and buy the resources or u can start free trial

**Comment by adejeg** [comment]
Oh, I use a pay-as-you-go plan and every other project I have on Azure are running perfectly, I actually deployed earlier but then it started failing all of a sudden

**Comment by adejeg** [comment]
This issue is from my PC, I tried deploying from a colleague's PC and it went through. Please how do I rectify this issue from my PC, any hint will be really appreciated.

**Comment by alexweininger** [comment]
@adejeg based on the logs you provided above, it looks like the zip being deployed is either extremely small, or empty. What sort of application are you trying to deploy? Make sure the build step is completing before the deploy starts.

> 19:54:11 hefa-iss: Starting deployment...
19:54:26 hefa-iss: Creating zip package...
19:54:26 hefa-iss: Zip package size: 22 B
19:54:32 hefa-iss: Fetching changes.
19:54:32 hefa-iss: Cleaning up temp folders from previous zip deployments and extracting pushed zip file C:\local\Temp\zipdeploy\3ruycmwv.zip (0.00 MB) to C:\local\Temp\zipdeploy\extracted
19:54:32 hefa-iss: Central Directory corrupt.
19:54:44 hefa-iss: Deployment failed.

**Comment by adejeg** [comment]
@alexweininger thank you for the feedback, I am trying to deploy an angular project, the project deploy when I moved it to another PC but I constantly get that error whenever I make a zip deploy using the Azure App Service extension on VS Code.


Although I changed the deployment method to GitHub Actions.

I get this error **The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.** whenever I refresh the page. I have a web.config file in my root folder but that is not working. 

This error started when I started deploying using Github Actions

Can you help me understand and fix the error?

**Comment by karrivinodh** [comment]
I think the url you are entered is wrong
