### ISSUE TITLE
Corrupt ZIP: end of central directory record signature not found

### ISSUE THREAD

**Issue by techiechap** [microsoft/vscode-azureappservice#2331]
When trying to download azure extensions,  "Tools Pack" VS code ends up with following error, vsix file also result in the same way,

Corrupt ZIP: end of central directory record signature not found

` [renderer1] [error] Corrupt ZIP: end of central directory record signature not found: Invalid: Corrupt ZIP: end of central directory record signature not found
    at $.downloadInstallableExtension (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:205704)
    at async $.doRun (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:20422`

**Comment by alexweininger** [comment]
Are you still facing this issue? This seems unrelated to our extensions and more related to VS Code extension installation process. 

If you're still experiencing this issue, try re-installing VS Code or the extension pack.
