### ISSUE TITLE
An error occurs in output panel when executing "Start Streaming Logs" action for a clean Linux web app

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#2580]
**OS:** All
**Build Version:** 20231009.14
**Regression:** Previous Release

**Repro Steps:**

1. Create a clean Linux web app.
2. Right click this web app and execute "Start Streaming Logs".
3. Check whether there is no error in output panel.

**Expect:**
There is no error in output panel, such as the below logs for Windows web apps.
![image](https://github.com/microsoft/vscode-azureappservice/assets/45614674/ea44469f-889e-4c47-868f-fda3f5d04af4)

**Actual:**
An error occurs in output panel.
![image](https://github.com/microsoft/vscode-azureappservice/assets/45614674/1b93b2b3-1bb9-4372-8df4-a4217c318c44)

**More Info:**
1. This issue does not reproduce for Windows web apps.
2. This issue does not reproduce after deploying project to web app.
3. This issue does not reproduce on the current released build v0.25.0, the screenshot shows as below.
![image](https://github.com/microsoft/vscode-azureappservice/assets/45614674/71690c27-eb1e-402d-85e0-17628d9be525)

**Comment by nturinski** [comment]
I think this is just an issue with the service running Docker. Even though the app is created, it took a while before I could actually browse my website.

When I tried starting the log stream on the portal, I was also having an error there. After restarting the app and verifying I could browse the website, the logs seemed to be working:

```
Connecting to log stream...
2023-10-10T16:39:30  Welcome, you are now connected to log-streaming service.
Error connecting to log-streaming service:
aborted
Connecting to log stream...
2023-10-10T16:42:03  Welcome, you are now connected to log-streaming service.
Starting Log Tail -n 10 of existing logs ----
/home/LogFiles/__lastCheckTime.txt  (https://naturins-node-linux.scm.azurewebsites.net/api/vfs/LogFiles/__lastCheckTime.txt)
10/10/2023 16:39:46
/home/LogFiles/kudu/trace/a993f8d317c1-0dd32665-ec0a-4f8f-92c5-2d0880212141.txt  (https://naturins-node-linux.scm.azurewebsites.net/api/vfs/LogFiles/kudu/trace/a993f8d317c1-0dd32665-ec0a-4f8f-92c5-2d0880212141.txt)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String , String , EnumerationOptions )
   at System.IO.Directory.InternalEnumeratePaths(String , String , SearchTarget , EnumerationOptions )
   at System.IO.Directory.GetFiles(String , String , EnumerationOptions )
   at System.IO.Directory.GetFiles(String , String , SearchOption )
   at Kudu.Services.Performance.LogStreamManager.GetFiles(String path, String ext) in /tmp/KuduLite/Kudu.Services/Diagnostics/LogStreamManager.cs:line 263
   at Kudu.Services.Performance.LogStreamManager.Initialize(String path, HttpContext context) in /tmp/KuduLite/Kudu.Services/Diagnostics/LogStreamManager.cs:line 309
   at Kudu.Services.Performance.LogStreamManager.ProcessRequest(HttpContext context) in /tmp/KuduLite/Kudu.Services/Diagnostics/LogStreamManager.cs:line 123
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Kudu.Services.Web.Tracing.TraceMiddleware.Invoke(HttpContext context) in /tmp/KuduLite/Kudu.Services.Web/Tracing/TraceMiddleware.cs:line 95
2023-10-10T16:37:57    Error occurred, type: error, text: LogStreamManager: Inside Reset
/home/LogFiles/kudu/trace/a993f8d317c1-386719ff-73c4-4060-a400-ebc87d703d6b.txt  (https://naturins-node-linux.scm.azurewebsites.net/api/vfs/LogFiles/kudu/trace/a993f8d317c1-386719ff-73c4-4060-a400-ebc87d703d6b.txt)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String , String , EnumerationOptions )
   at System.IO.Directory.InternalEnumeratePaths(String , String , SearchTarget , EnumerationOptions )
   at System.IO.Directory.GetFiles(String , String , EnumerationOptions )
   at System.IO.Directory.GetFiles(String , String , SearchOption )
   at Kudu.Services.Performance.LogStreamManager.GetFiles(String path, String ext) in /tmp/KuduLite/Kudu.Services/Diagnostics/LogStreamManager.cs:line 263
   at Kudu.Services.Performance.LogStreamManager.Initialize(String path, HttpContext context) in /tmp/KuduLite/Kudu.Services/Diagnostics/LogStreamManager.cs:line 309
   at Kudu.Services.Performance.LogStreamManager.ProcessRequest(HttpContext context) in /tmp/KuduLite/Kudu.Services/Diagnostics/LogStreamManager.cs:line 123
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Kudu.Services.Web.Tracing.TraceMiddleware.Invoke(HttpContext context) in /tmp/KuduLite/Kudu.Services.Web/Tracing/TraceMiddleware.cs:line 95
2023-10-10T16:37:58    Error occurred, type: error, text: LogStreamManager: Inside Reset
/home/LogFiles/kudu/trace/a993f8d317c1-55a8f59a-bad9-46e3-aecf-3b44797a47ed.txt  (https://naturins-node-linux.scm.azurewebsites.net/api/vfs/LogFiles/kudu/trace/a993f8d317c1-55a8f59a-bad9-46e3-aecf-3b44797a47ed.txt)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String , String , EnumerationOptions )
   at System.IO.Directory.InternalEnumeratePaths(String , String , SearchTarget , EnumerationOptions )
   at System.IO.Directory.GetFiles(String , String , EnumerationOptions )
   at System.IO.Directory.GetFiles(String , String , SearchOption )
   at Kudu.Services.Performance.LogStreamManager.GetFiles(String path, String ext) in /tmp/KuduLite/Kudu.Services/Diagnostics/LogStreamManager.cs:line 263
   at Kudu.Services.Performance.LogStreamManager.Initialize(String path, HttpContext context) in /tmp/KuduLite/Kudu.Services/Diagnostics/LogStreamManager.cs:line 309
   at Kudu.Services.Performance.LogStreamManager.ProcessRequest(HttpContext context) in /tmp/KuduLite/Kudu.Services/Diagnostics/LogStreamManager.cs:line 123
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Kudu.Services.Web.Tracing.TraceMiddleware.Invoke(HttpContext context) in /tmp/KuduLite/Kudu.Services.Web/Tracing/TraceMiddleware.cs:line 95
2023-10-10T16:37:57    Error occurred, type: error, text: LogStreamManager: Inside Reset
/home/LogFiles/kudu/trace/a993f8d317c1-938fbe45-0aeb-444c-9729-1273d4f87ba9.txt  (https://naturins-node-linux.scm.azurewebsites.net/api/vfs/LogFiles/kudu/trace/a993f8d317c1-938fbe45-0aeb-444c-9729-1273d4f87ba9.txt)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String , String , EnumerationOptions )
   at System.IO.Directory.InternalEnumeratePaths(String , String , SearchTarget , EnumerationOptions )
   at System.IO.Directory.GetFiles(String , String , EnumerationOptions )
   at System.IO.Directory.GetFiles(String , String , SearchOption )
   at Kudu.Services.Performance.LogStreamManager.GetFiles(String path, String ext) in /tmp/KuduLite/Kudu.Services/Diagnostics/LogStreamManager.cs:line 263
   at Kudu.Services.Performance.LogStreamManager.Initialize(String path, HttpContext context) in /tmp/KuduLite/Kudu.Services/Diagnostics/LogStreamManager.cs:line 309
   at Kudu.Services.Performance.LogStreamManager.ProcessRequest(HttpContext context) in /tmp/KuduLite/Kudu.Services/Diagnostics/LogStreamManager.cs:line 123
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Kudu.Services.Web.Tracing.TraceMiddleware.Invoke(HttpContext context) in /tmp/KuduLite/Kudu.Services.Web/Tracing/TraceMiddleware.cs:line 95
2023-10-10T16:37:58    Error occurred, type: error, text: LogStreamManager: Inside Reset
/home/LogFiles/kudu/trace/a993f8d317c1-b44c797a-1663-4614-a2d4-0f4e8f27ec6c.txt  (https://naturins-node-linux.scm.azurewebsites.net/api/vfs/LogFiles/kudu/trace/a993f8d317c1-b44c797a-1663-4614-a2d4-0f4e8f27ec6c.txt)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String , String , EnumerationOptions )
   at System.IO.Directory.InternalEnumeratePaths(String , String , SearchTarget , EnumerationOptions )
   at System.IO.Directory.GetFiles(String , String , EnumerationOptions )
   at Kudu.Services.Performance.LogStreamManager.GetFiles(String path, String ext) in /tmp/KuduLite/Kudu.Services/Diagnostics/LogStreamManager.cs:line 269
   at Kudu.Services.Performance.LogStreamManager.Initialize(String path, HttpContext context) in /tmp/KuduLite/Kudu.Services/Diagnostics/LogStreamManager.cs:line 347
   at Kudu.Services.Performance.LogStreamManager.ProcessRequest(HttpContext context) in /tmp/KuduLite/Kudu.Services/Diagnostics/LogStreamManager.cs:line 212
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Kudu.Services.Web.Tracing.TraceMiddleware.Invoke(HttpContext context) in /tmp/KuduLite/Kudu.Services.Web/Tracing/TraceMiddleware.cs:line 105
2023-10-10T16:39:29    Error occurred, type: error, text: LogStreamManager: Inside Reset
/home/LogFiles/kudu/trace/a993f8d317c1-d0ea8b1d-c97f-4364-a5b7-a958ad93193b.txt  (https://naturins-node-linux.scm.azurewebsites.net/api/vfs/LogFiles/kudu/trace/a993f8d317c1-d0ea8b1d-c97f-4364-a5b7-a958ad93193b.txt)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String , String , EnumerationOptions )
   at System.IO.Directory.InternalEnumeratePaths(String , String , SearchTarget , EnumerationOptions )
   at System.IO.Directory.GetFiles(String , String , EnumerationOptions )
   at Kudu.Services.Performance.LogStreamManager.GetFiles(String path, String ext) in /tmp/KuduLite/Kudu.Services/Diagnostics/LogStreamManager.cs:line 269
   at Kudu.Services.Performance.LogStreamManager.Initialize(String path, HttpContext context) in /tmp/KuduLite/Kudu.Services/Diagnostics/LogStreamManager.cs:line 347
   at Kudu.Services.Performance.LogStreamManager.ProcessRequest(HttpContext context) in /tmp/KuduLite/Kudu.Services/Diagnostics/LogStreamManager.cs:line 212
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Kudu.Services.Web.Tracing.TraceMiddleware.Invoke(HttpContext context) in /tmp/KuduLite/Kudu.Services.Web/Tracing/TraceMiddleware.cs:line 105
2023-10-10T16:39:30    Error occurred, type: error, text: LogStreamManager: Inside Reset
/home/LogFiles/kudu/trace/a993f8d317c1-f4a6a8d9-eb11-4eab-9e9e-896183bfd046.txt  (https://naturins-node-linux.scm.azurewebsites.net/api/vfs/LogFiles/kudu/trace/a993f8d317c1-f4a6a8d9-eb11-4eab-9e9e-896183bfd046.txt)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String , String , EnumerationOptions )
   at System.IO.Directory.InternalEnumeratePaths(String , String , SearchTarget , EnumerationOptions )
   at System.IO.Directory.GetFiles(String , String , EnumerationOptions )
   at System.IO.Directory.GetFiles(String , String , SearchOption )
   at Kudu.Services.Performance.LogStreamManager.GetFiles(String path, String ext) in /tmp/KuduLite/Kudu.Services/Diagnostics/LogStreamManager.cs:line 263
   at Kudu.Services.Performance.LogStreamManager.Initialize(String path, HttpContext context) in /tmp/KuduLite/Kudu.Services/Diagnostics/LogStreamManager.cs:line 309
   at Kudu.Services.Performance.LogStreamManager.ProcessRequest(HttpContext context) in /tmp/KuduLite/Kudu.Services/Diagnostics/LogStreamManager.cs:line 123
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Kudu.Services.Web.Tracing.TraceMiddleware.Invoke(HttpContext context) in /tmp/KuduLite/Kudu.Services.Web/Tracing/TraceMiddleware.cs:line 95
2023-10-10T16:38:00    Error occurred, type: error, text: LogStreamManager: Inside Reset
/home/LogFiles/2023_10_10_lw1sdlwk0006DS_default_docker.log  (https://naturins-node-linux.scm.azurewebsites.net/api/vfs/LogFiles/2023_10_10_lw1sdlwk0006DS_default_docker.log)
/home/LogFiles/2023_10_10_lw1sdlwk0006DS_docker.log  (https://naturins-node-linux.scm.azurewebsites.net/api/vfs/LogFiles/2023_10_10_lw1sdlwk0006DS_docker.log)
Ending Log Tail of existing logs ---
Starting Live Log Stream ---
2023-10-10T16:43:03  No new trace in the past 1 min(s).
```
