### ISSUE TITLE
Streaming logs no longer show app output

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-azureappservice#309]
Discovered this when attempting to troubleshoot an app issue. When connected to the streaming logs, I only see this output. None of the output for my app is showing up.

```sh
2018-02-26 17:03:08.241 INFO  - Container maherna-mvp-todo_1 for site maherna-mvp-todo initialized successfully.
2018-02-26 17:03:09.675 INFO  - Starting container for site
2018-02-26 17:03:09.676 INFO  - docker run -d -p 34000:8080 --name maherna-mvp-todo_2
2018-02-26T17:03:24  Startup Request, url: /Default.cshtml, method: GET, type: request, pid: 54,1,12, SCM_BIN_PATH: /opt/Kudu/bin, SCM_SKIP_SSL_VALIDATION: 0, ScmType: None
2018-02-26 17:03:33.187 INFO  - Container maherna-mvp-todo_2 for site maherna-mvp-todo initialized successfully.
```

The app fails to connect so I know there's an issue.. in the Kudu console's logs (`123_docker.log`), I see this output.

```sh
2018-02-26T17:03:32.511354813Z 17:03:32 0|server   | App listening on port 8080
2018-02-26T17:03:32.548047958Z 17:03:32 0|server   | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
2018-02-26T17:03:32.549451129Z 17:03:32 0|server   | Error: Password contains an illegal unescaped character
2018-02-26T17:03:32.549765445Z 17:03:32 0|server   |     at parseConnectionString (/home/site/wwwroot/node_modules/mongodb/lib/url_parser.js:281:13)
2018-02-26T17:03:32.550058559Z 17:03:32 0|server   |     at parseHandler (/home/site/wwwroot/node_modules/mongodb/lib/url_parser.js:113:14)
2018-02-26T17:03:32.550408877Z 17:03:32 0|server   |     at module.exports (/home/site/wwwroot/node_modules/mongodb/lib/url_parser.js:19:12)
2018-02-26T17:03:32.550726493Z 17:03:32 0|server   |     at Promise (/home/site/wwwroot/node_modules/mongoose/lib/connection.js:332:5)
2018-02-26T17:03:32.551074411Z 17:03:32 0|server   |     at Promise (<anonymous>)
...
```

**Comment by nturinski** [comment]
@fiveisprime What kind of app is this?  Is this through the appservice extension?  I looked at the kudu streaing logs for a Linux and Windows app and it didn't have any connection problems.

**Comment by EricJizbaMSFT** [comment]
Also worth noting - @fiveisprime are you testing on master? Could you try testing on the latest released version and see if it also repros?

**Comment by fiveisprime** [comment]
I'm installed from the market so 0.5.1.
This is a Linux app running on node@8

**Comment by fiveisprime** [comment]
I'm going to just say this was an oddity. I tried this again after a few meetings and it's working as expected now. 🤷‍♀️
