### ISSUE TITLE
local-git deployment with Python, directory not empty

### ISSUE THREAD

**Issue by tiloc** [microsoft/vscode-azureappservice#901]
I am using local-git deployment from the terminal with "git push azure master". When I do this for the first time with a newly created app service it works well. However, on most subsequent attempts, I am getting messages to the effect that a directory is not empty. I am attaching an example, but this happens for other packages as well, so doesn't seem to be related to the package. Maybe the proposals from https://stackoverflow.com/questions/303200/how-do-i-remove-delete-a-folder-that-is-not-empty-with-python might help with tougher replacements for the failing shutil.rmtree call (which is intentionally designed to fail on non-empty directories).

.....
Using cached https://files.pythonhosted.org/packages/fd/2a/b51377ab9826f0551da19951257d2434f46329cd6cfdf9592ea9ca5f6034/whitenoise-4.1.2-py2.py3-none-any.whl
remote:    Installing collected packages: aniso8601, asn1crypto, certifi, pycparser, cffi, chardet, colorama, itypes, MarkupSafe, Jinja2, coreschema, uritemplate, idna, urllib3, requests, coreapi, six, cryptography, defusedxml, pytz, Django, django-cors-headers, sqlparse, django-debug-toolbar, django-filter, promise, Rx, graphql-core, graphql-relay, graphene, singledispatch, graphene-django, django-graphiql-debug-toolbar, django-split-settings, djangorestframework, PyJWT, djangorestframework-jwt, docutils, ecdsa, isodate, fhirclient, future, oauthlib, psycopg2, pyasn1, rsa, python-jose, python3-openid, requests-oauthlib, social-auth-core, social-auth-app-django, whitenoise
remote: ..
remote: Exception:
remote: Traceback (most recent call last):
remote:   File "/opt/python/3.7.1/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 143, in main
remote:     status = self.run(options, args)
remote:   File "/opt/python/3.7.1/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 414, in run
remote:     options.target_dir, target_temp_dir, options.upgrade
remote:   File "/opt/python/3.7.1/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 465, in _handle_target_dir
remote:     shutil.rmtree(target_item_dir)
remote:   File "/opt/python/3.7.1/lib/python3.7/shutil.py", line 489, in rmtree
remote:     onerror(os.rmdir, path, sys.exc_info())
remote:   File "/opt/python/3.7.1/lib/python3.7/shutil.py", line 487, in rmtree
remote:     os.rmdir(path)
remote: OSError: [Errno 39] Directory not empty: '/home/site/wwwroot/__oryx_packages__/markupsafe'
remote: You are using pip version 18.1, however version 19.0.3 is available.
remote: You should consider upgrading via the 'pip install --upgrade pip' command.
remote:    Successfully installed Django-2.1.7 Jinja2-2.10 MarkupSafe-1.1.1 PyJWT-1.7.1
....

**Comment by nturinski** [comment]
Hi @tiloc,

Sorry about this issue.  I'm not sure that our extension is able to do much about this error.  Could you please create an issue at this repo:https://github.com/microsoft/oryx

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of activity
